// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPR2Zeyjjy388n7CT38dopaIu6yfUyJPQ',
    appId: '1:410935031541:web:ccb148a8ecf4b28e7937bc',
    messagingSenderId: '410935031541',
    projectId: 'clone-2-43296',
    authDomain: 'clone-2-43296.firebaseapp.com',
    storageBucket: 'clone-2-43296.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbaaJYA4zOobYsuILst_3VTo3-mKzTgtQ',
    appId: '1:410935031541:android:ba34316b176222dc7937bc',
    messagingSenderId: '410935031541',
    projectId: 'clone-2-43296',
    storageBucket: 'clone-2-43296.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_jVh5JbNqJrOeIs_p42HEvf-hQoDW-8o',
    appId: '1:410935031541:ios:874e1980d9f26da07937bc',
    messagingSenderId: '410935031541',
    projectId: 'clone-2-43296',
    storageBucket: 'clone-2-43296.appspot.com',
    iosClientId: '410935031541-bme1g89dec3n95ivpi6mof8620cr5qbo.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonclone2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_jVh5JbNqJrOeIs_p42HEvf-hQoDW-8o',
    appId: '1:410935031541:ios:f28273dcc56e37f27937bc',
    messagingSenderId: '410935031541',
    projectId: 'clone-2-43296',
    storageBucket: 'clone-2-43296.appspot.com',
    iosClientId: '410935031541-715sak78a5opj474o8u39q5j848n64hq.apps.googleusercontent.com',
    iosBundleId: 'com.example.amazonclone2.RunnerTests',
  );
}
